services:
  - type: web
    name: analisador-rivas
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    repo: https://github.com/thiagotqp/analisador-rivas
